### ISSUE TITLE
USER STORY: Creating a new booking

### ISSUE THREAD

**Issue by astro-mat** [astro-mat/StudioMooMooPortal_PP4#14]
EPIC: <epic> #11 Studio Booking System

As a **registered user** I can **book a slot** so that **I can secure my place to use the studio**

- Acceptance criteria 1: The user can specify when they would like to use the studio.

- Acceptance criteria 2: The user can specify equipment requirements.

- Acceptance criteria 3: There is confirmation of the booking.

**tasks**

- [ ] Design and implement new booking form. 
- [ ] Add booking validation and error handling. 
- [ ] Test booking creation functionality
