### ISSUE TITLE
USER STORY: Django installation and configuration

### ISSUE THREAD

**Issue by astro-mat** [astro-mat/StudioMooMooPortal_PP4#2]
**Epic**  #3 Initial project setup

As a **developer**, I can **install Django and support libraries** so that **I have the appropriate environment ready to be able to proceed with the development**

Acceptance Criteria:

- Acceptance criteria 1
When the project is opened in the browser the web page shows that there has been a successful installation.

**tasks**
- [x] Install Django and gunicorn
- [x] Install supporting libraries
- [x] Create requirements file
- [x] Create booking project and app
- [x] Update settings.py file
- [x] Run migrations
