### ISSUE TITLE
Hosting setup and configuration

### ISSUE THREAD

**Issue by astro-mat** [astro-mat/StudioMooMooPortal_PP4#4]
EPIC: #3 Initial project setup 

As a **developer** I can **create a hosting environment** so that **I can present the site to the end user**

- Acceptance criteria 1
 When the project app is opened on Heroku, the browser the web page shows that there has been a successful installation.

**tasks**

- [ ] Create Heroku app
- [ ] Create a database on ElephantSQL
- [ ] Create an env.py file
- [ ] Modify settings.py
- [ ] Update Heroku Config Vars
- [ ] Prepare the Cloudinary storage for static and media files
- [ ] Run the deployment
